apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pu9cpmh2y-nodejs 
  janus-idp.io/tekton: pu9cpmh2y-nodejs
  backstage.io/kubernetes-id: pu9cpmh2y-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pu9cpmh2y-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  